DETAILED_REP_SOIL_LAYOUT_1 = {
    "layers": [
        {
            "soil": {"name": "Deklaag", "color": (157, 78, 64), "properties": {}},
            "top_of_layer": 4.625,
            "bottom_of_layer": 1.875,
            "properties": {
                "aquifer": False,
                "gamma_wet": 16,
                "gamma_dry": 16,
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "grain_size_d70": None,
            },
        },
        {
            "soil": {"name": "Klei diep", "color": (157, 78, 64), "properties": {}},
            "top_of_layer": 1.875,
            "bottom_of_layer": 1.375,
            "properties": {
                "aquifer": False,
                "gamma_wet": 16,
                "gamma_dry": 16,
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "grain_size_d70": None,
            },
        },
        {
            "soil": {"name": "Deklaag", "color": (157, 78, 64), "properties": {}},
            "top_of_layer": 1.375,
            "bottom_of_layer": 1.125,
            "properties": {
                "aquifer": False,
                "gamma_wet": 16,
                "gamma_dry": 16,
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "grain_size_d70": None,
            },
        },
        {
            "soil": {"name": "Klei diep", "color": (157, 78, 64), "properties": {}},
            "top_of_layer": 1.125,
            "bottom_of_layer": -0.125,
            "properties": {
                "aquifer": False,
                "gamma_wet": 16,
                "gamma_dry": 16,
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "grain_size_d70": None,
            },
        },
        {
            "soil": {"name": "Zand, los gepakt", "color": (255, 255, 0), "properties": {}},
            "top_of_layer": -0.125,
            "bottom_of_layer": -6.625,
            "properties": {
                "aquifer": True,
                "gamma_wet": 19,
                "gamma_dry": 17,
                "vertical_permeability": 0.0001,
                "horizontal_permeability": 0.0001,
                "grain_size_d70": 250,
            },
        },
        {
            "soil": {"name": "Zand, vast gepakt", "color": (255, 255, 0), "properties": {}},
            "top_of_layer": -6.625,
            "bottom_of_layer": -6.875,
            "properties": {
                "aquifer": True,
                "gamma_wet": 21,
                "gamma_dry": 19,
                "vertical_permeability": 0.0001,
                "horizontal_permeability": 0.0001,
                "grain_size_d70": 330,
            },
        },
        {
            "soil": {"name": "Zand, los gepakt", "color": (255, 255, 0), "properties": {}},
            "top_of_layer": -6.875,
            "bottom_of_layer": -7.375,
            "properties": {
                "aquifer": True,
                "gamma_wet": 19,
                "gamma_dry": 17,
                "vertical_permeability": 0.0001,
                "horizontal_permeability": 0.0001,
                "grain_size_d70": 250,
            },
        },
        {
            "soil": {"name": "Klei diep", "color": (157, 78, 64), "properties": {}},
            "top_of_layer": -7.375,
            "bottom_of_layer": -7.625,
            "properties": {
                "aquifer": False,
                "gamma_wet": 16,
                "gamma_dry": 16,
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "grain_size_d70": None,
            },
        },
        {
            "soil": {"name": "Zand, los gepakt", "color": (255, 255, 0), "properties": {}},
            "top_of_layer": -7.625,
            "bottom_of_layer": -9.625,
            "properties": {
                "aquifer": True,
                "gamma_wet": 19,
                "gamma_dry": 17,
                "vertical_permeability": 0.0001,
                "horizontal_permeability": 0.0001,
                "grain_size_d70": 250,
            },
        },
    ]
}

SIMPLIFIED_REP_SOIL_LAYOUT_1 = {
    "layers": [
        {
            "soil": {"name": "cover_layer", "color": (192, 192, 192), "properties": {"ui_name": "Deklaag"}},
            "top_of_layer": 4.625,
            "bottom_of_layer": -0.125,
            "properties": {
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "gamma_dry": 16.0,
                "gamma_wet": 16.0,
                "grain_size_d70": None,
                "aquifer": False,
            },
        },
        {
            "soil": {"name": "first_aquifer", "color": (202, 188, 145), "properties": {"ui_name": "Eerste aquifer"}},
            "top_of_layer": -0.125,
            "bottom_of_layer": -7.375,
            "properties": {
                "vertical_permeability": None,
                "horizontal_permeability": 0.0001,
                "gamma_dry": 17.666666666666668,
                "gamma_wet": 19.666666666666668,
                "grain_size_d70": 250,
                "aquifer": True,
            },
        },
        {
            "soil": {
                "name": "intermediate_aquitard",
                "color": (154, 205, 50),
                "properties": {"ui_name": "Tussenliggende aquitard"},
            },
            "top_of_layer": -7.375,
            "bottom_of_layer": -7.625,
            "properties": {
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "gamma_dry": 16.0,
                "gamma_wet": 16.0,
                "grain_size_d70": None,
                "aquifer": False,
            },
        },
        {
            "soil": {"name": "second_aquifer", "color": (219, 209, 180), "properties": {"ui_name": "Tweede aquifer"}},
            "top_of_layer": -7.625,
            "bottom_of_layer": -9.625,
            "properties": {
                "vertical_permeability": None,
                "horizontal_permeability": 0.0001,
                "gamma_dry": 17.0,
                "gamma_wet": 19.0,
                "grain_size_d70": 250,
                "aquifer": True,
            },
        },
    ]
}

DETAILED_REP_SOIL_LAYOUT_2 = {
    "layers": [
        {
            "soil": {"name": "Deklaag", "color": (157, 78, 64), "properties": {}},
            "top_of_layer": 4.625,
            "bottom_of_layer": 1.875,
            "properties": {
                "aquifer": False,
                "gamma_wet": 16,
                "gamma_dry": 16,
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "grain_size_d70": None,
            },
        },
        {
            "soil": {"name": "Klei diep", "color": (157, 78, 64), "properties": {}},
            "top_of_layer": 1.875,
            "bottom_of_layer": 1.375,
            "properties": {
                "aquifer": False,
                "gamma_wet": 16,
                "gamma_dry": 16,
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "grain_size_d70": None,
            },
        },
        {
            "soil": {"name": "Deklaag", "color": (157, 78, 64), "properties": {}},
            "top_of_layer": 1.375,
            "bottom_of_layer": 1.125,
            "properties": {
                "aquifer": False,
                "gamma_wet": 16,
                "gamma_dry": 16,
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "grain_size_d70": None,
            },
        },
        {
            "soil": {"name": "Klei diep", "color": (157, 78, 64), "properties": {}},
            "top_of_layer": 1.125,
            "bottom_of_layer": -0.125,
            "properties": {
                "aquifer": False,
                "gamma_wet": 16,
                "gamma_dry": 16,
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "grain_size_d70": None,
            },
        },
        {
            "soil": {"name": "Zand, los gepakt", "color": (255, 255, 0), "properties": {}},
            "top_of_layer": -0.125,
            "bottom_of_layer": -6.625,
            "properties": {
                "aquifer": True,
                "gamma_wet": 19,
                "gamma_dry": 17,
                "vertical_permeability": 0.0001,
                "horizontal_permeability": 0.0001,
                "grain_size_d70": 250,
            },
        },
        {
            "soil": {"name": "Zand, vast gepakt", "color": (255, 255, 0), "properties": {}},
            "top_of_layer": -6.625,
            "bottom_of_layer": -6.875,
            "properties": {
                "aquifer": True,
                "gamma_wet": 21,
                "gamma_dry": 19,
                "vertical_permeability": 0.0001,
                "horizontal_permeability": 0.0001,
                "grain_size_d70": 330,
            },
        },
        {
            "soil": {"name": "Zand, los gepakt", "color": (255, 255, 0), "properties": {}},
            "top_of_layer": -6.875,
            "bottom_of_layer": -7.375,
            "properties": {
                "aquifer": True,
                "gamma_wet": 19,
                "gamma_dry": 17,
                "vertical_permeability": 0.0001,
                "horizontal_permeability": 0.0001,
                "grain_size_d70": 250,
            },
        },
    ]
}

SIMPLIFIED_REP_SOIL_LAYOUT_2 = {
    "layers": [
        {
            "soil": {"name": "cover_layer", "color": (192, 192, 192), "properties": {}},
            "top_of_layer": 4.625,
            "bottom_of_layer": -0.125,
            "properties": {
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "gamma_dry": 16.0,
                "gamma_wet": 16.0,
                "grain_size_d70": None,
                "aquifer": False,
            },
        },
        {
            "soil": {"name": "first_aquifer", "color": (202, 188, 145), "properties": {}},
            "top_of_layer": -0.125,
            "bottom_of_layer": -7.375,
            "properties": {
                "vertical_permeability": None,
                "horizontal_permeability": 0.0001,
                "gamma_dry": 17.666666666666668,
                "gamma_wet": 19.666666666666668,
                "grain_size_d70": 250,
                "aquifer": True,
            },
        },
        {
            "soil": {"name": "intermediate_aquitard", "color": (154, 205, 50), "properties": {}},
            "top_of_layer": -7.375,
            "bottom_of_layer": -7.625,
            "properties": {
                "vertical_permeability": 1e-08,
                "horizontal_permeability": 1e-08,
                "gamma_dry": 16.0,
                "gamma_wet": 16.0,
                "grain_size_d70": None,
                "aquifer": False,
            },
        },
    ]
}

SELLMEIJER_DOUBLE_AQUIFER_RES = {
    "uplift": [
        {
            "Sloot": "Nee",
            "uc": 2.036519966316536,
            "z score": 2.9799949031600406,
            "DeklaagDikte [m]": 6.25,
            "Maaiveld [m NAP]": 2.125,
            "RivierPeil [m NAP]": 5,
            "KritiekStijghoogteVerschilOpbarsten [m]": 5.854994903160041,
            "StijghoogteWaterVoerendPakketBijUittredepunt [m NAP]": 5,
            "FreatischNiveauUittredepunt [m NAP]": 2.125,
            "aquifer": 1,
            "exit_point": "exit_point_1",
        },
        {
            "Sloot": "Nee",
            "uc": 1.945864710124782,
            "z score": 2.7193610416087477,
            "DeklaagDikte [m]": 6.25,
            "Maaiveld [m NAP]": 2.125,
            "RivierPeil [m NAP]": 5,
            "KritiekStijghoogteVerschilOpbarsten [m]": 5.594361041608748,
            "StijghoogteWaterVoerendPakketBijUittredepunt [m NAP]": 5,
            "FreatischNiveauUittredepunt [m NAP]": 2.125,
            "aquifer": 2,
            "exit_point": "exit_point_1",
        },
    ],
    "heave": [
        {
            "Sloot": "Nee",
            "uc": 0.6521739130434782,
            "DeklaagDikte [m]": 6.25,
            "Maaiveld [m NAP]": 2.125,
            "z score": -0.16000000000000003,
            "KritiekStijghoogteVerschilOpbarsten [m]": 5.854994903160041,
            "StijghoogteWaterVoerendPakketBijUittredepunt [m NAP]": 5,
            "KritiekeGradientHeave": 0.3,
            "aquifer": 1,
            "exit_point": "exit_point_1",
        },
        {
            "Sloot": "Nee",
            "uc": 0.6521739130434782,
            "DeklaagDikte [m]": 6.25,
            "Maaiveld [m NAP]": 2.125,
            "z score": -0.16000000000000003,
            "KritiekStijghoogteVerschilOpbarsten [m]": 5.594361041608748,
            "StijghoogteWaterVoerendPakketBijUittredepunt [m NAP]": 5,
            "KritiekeGradientHeave": 0.3,
            "aquifer": 2,
            "exit_point": "exit_point_1",
        },
    ],
    "sellmeijer": [
        {
            "Sloot": "Nee",
            "FreatischNiveauUittredepunt [m NAP]": 2.125,
            "RivierPeil [m NAP]": 5,
            "DeklaagDikte [m]": 6.25,
            "AquiferDikte [m]": 3.25,
            "AquiferDarcyDoorlatenheid [m/d]": 2.5900000000000003,
            "AquiferIntrinsiekDoorlatenkeid [m/s]": 4.0641399554498436e-12,
            "d70_m [mm]": 0.00025,
            "m_p [-]": 1.0,
            "f_1 [-]": 0.3109082586942976,
            "CoefficientvanWhite [-]": 0.25,
            "Theta [-]": 37.0,
            "d70_ref [mm]": 0.000208,
            "R_c": 0.3,
            "f_2 [-]": 0.340901679928021,
            "f_3 [-]": 1.899432269668164,
            "KwelwegLengte [m]": 69.69248238339287,
            "KritiekVervalPipingSellmeijer [m]": 14.030435312482394,
            "GereduceerdOptredendVerval [m]": 1.0,
            "uc": 14.030435312482394,
            "aquifer": 1,
            "exit_point": "exit_point_1",
        },
        {
            "Sloot": "Nee",
            "FreatischNiveauUittredepunt [m NAP]": 2.125,
            "RivierPeil [m NAP]": 5,
            "DeklaagDikte [m]": 6.25,
            "AquiferDikte [m]": 5.0,
            "AquiferDarcyDoorlatenheid [m/d]": 2.59,
            "AquiferIntrinsiekDoorlatenkeid [m/s]": 4.064139955449843e-12,
            "d70_m [mm]": 0.00033,
            "m_p [-]": 1.0,
            "f_1 [-]": 0.3109082586942976,
            "CoefficientvanWhite [-]": 0.25,
            "Theta [-]": 37.0,
            "d70_ref [mm]": 0.000208,
            "R_c": 0.3,
            "f_2 [-]": 0.38094187395547,
            "f_3 [-]": 1.7133801220913267,
            "KwelwegLengte [m]": 69.69248238339287,
            "KritiekVervalPipingSellmeijer [m]": 14.142644682125418,
            "GereduceerdOptredendVerval [m]": 1.0,
            "uc": 14.142644682125418,
            "aquifer": 2,
            "exit_point": "exit_point_1",
        },
    ],
}

SELLMEIJER_SINGLE_AQUIFER_RES = {
    "uplift": [
        {
            "Sloot": "Nee",
            "uc": 2.036519966316536,
            "z score": 2.9799949031600406,
            "DeklaagDikte [m]": 6.25,
            "Maaiveld [m NAP]": 2.125,
            "RivierPeil [m NAP]": 5,
            "KritiekStijghoogteVerschilOpbarsten [m]": 5.854994903160041,
            "StijghoogteWaterVoerendPakketBijUittredepunt [m NAP]": 5,
            "FreatischNiveauUittredepunt [m NAP]": 2.125,
            "aquifer": 1,
            "exit_point": "exit_point_1",
        },
        {
            "Sloot": "Nee",
            "uc": 1.945864710124782,
            "z score": 2.7193610416087477,
            "DeklaagDikte [m]": 6.25,
            "Maaiveld [m NAP]": 2.125,
            "RivierPeil [m NAP]": 5,
            "KritiekStijghoogteVerschilOpbarsten [m]": 5.594361041608748,
            "StijghoogteWaterVoerendPakketBijUittredepunt [m NAP]": 5,
            "FreatischNiveauUittredepunt [m NAP]": 2.125,
            "aquifer": 2,
            "exit_point": "exit_point_1",
        },
    ],
    "heave": [
        {
            "Sloot": "Nee",
            "uc": 0.6521739130434782,
            "DeklaagDikte [m]": 6.25,
            "Maaiveld [m NAP]": 2.125,
            "z score": -0.16000000000000003,
            "KritiekStijghoogteVerschilOpbarsten [m]": 5.854994903160041,
            "StijghoogteWaterVoerendPakketBijUittredepunt [m NAP]": 5,
            "KritiekeGradientHeave": 0.3,
            "aquifer": 1,
            "exit_point": "exit_point_1",
        },
        {
            "Sloot": "Nee",
            "uc": 0.6521739130434782,
            "DeklaagDikte [m]": 6.25,
            "Maaiveld [m NAP]": 2.125,
            "z score": -0.16000000000000003,
            "KritiekStijghoogteVerschilOpbarsten [m]": 5.594361041608748,
            "StijghoogteWaterVoerendPakketBijUittredepunt [m NAP]": 5,
            "KritiekeGradientHeave": 0.3,
            "aquifer": 2,
            "exit_point": "exit_point_1",
        },
    ],
    "sellmeijer": [
        {
            "Sloot": "Nee",
            "FreatischNiveauUittredepunt [m NAP]": 2.125,
            "RivierPeil [m NAP]": 5,
            "DeklaagDikte [m]": 6.25,
            "AquiferDikte [m]": 3.25,
            "AquiferDarcyDoorlatenheid [m/d]": 2.5900000000000003,
            "AquiferIntrinsiekDoorlatenkeid [m/s]": 4.0641399554498436e-12,
            "d70_m [mm]": 0.00025,
            "m_p [-]": 1.0,
            "f_1 [-]": 0.3109082586942976,
            "CoefficientvanWhite [-]": 0.25,
            "Theta [-]": 37.0,
            "d70_ref [mm]": 0.000208,
            "R_c": 0.3,
            "f_2 [-]": 0.340901679928021,
            "f_3 [-]": 1.899432269668164,
            "KwelwegLengte [m]": 69.69248238339287,
            "KritiekVervalPipingSellmeijer [m]": 14.030435312482394,
            "GereduceerdOptredendVerval [m]": 1.0,
            "uc": 14.030435312482394,
            "aquifer": 1,
            "exit_point": "exit_point_1",
        },
        {
            "Sloot": "Nee",
            "FreatischNiveauUittredepunt [m NAP]": 2.125,
            "RivierPeil [m NAP]": 5,
            "DeklaagDikte [m]": 6.25,
            "AquiferDikte [m]": 5.0,
            "AquiferDarcyDoorlatenheid [m/d]": 2.59,
            "AquiferIntrinsiekDoorlatenkeid [m/s]": 4.064139955449843e-12,
            "d70_m [mm]": 0.00033,
            "m_p [-]": 1.0,
            "f_1 [-]": 0.3109082586942976,
            "CoefficientvanWhite [-]": 0.25,
            "Theta [-]": 37.0,
            "d70_ref [mm]": 0.000208,
            "R_c": 0.3,
            "f_2 [-]": 0.38094187395547,
            "f_3 [-]": 1.7133801220913267,
            "KwelwegLengte [m]": 69.69248238339287,
            "KritiekVervalPipingSellmeijer [m]": 14.142644682125418,
            "GereduceerdOptredendVerval [m]": 1.0,
            "uc": 14.142644682125418,
            "aquifer": 2,
            "exit_point": "exit_point_1",
        },
    ],
}

SCENARIO_EXCEL_RESULTS = {
    "name_of_scenario": "Scenario 1",
    "weight_of_scenario": None,
    "bottom_of_soil_layout": -10.125,
    "soil_layout_table": [
        {"name": "Deklaag", "top_of_layer": 5.125, "aquifer": False},
        {"name": "Holoceen zand", "top_of_layer": -0.375, "aquifer": True},
        {"name": "inter", "top_of_layer": -3.625, "aquifer": False},
        {"name": "Pleistoceen zand", "top_of_layer": -5.125, "aquifer": True},
    ],
    "first_aquifer_permeability": 2.5900000000000003,
    "first_aquifer_d70": 0.25,
    "second_aquifer_activate": True,
    "second_aquifer_permeability": 2.59,
    "second_aquifer_d70": 0.33,
    "leakage_lengths": {
        "leakage_length_hinterland_first_aquifer": None,
        "leakage_length_hinterland_second_aquifer": None,
        "leakage_length_foreland_first_aquifer": None,
        "leakage_length_foreland_second_aquifer": None,
    },
}
