from viktor import Color
from viktor.parametrization import OptionListElement
from viktor.views import MapLegend

CPT_COLOR = Color.from_hex("#a86832")
BORE_COLOR = Color.from_hex("#f55442")

CPT_MAP_ICON = "triangle-filled"

DEFAULT_MIN_LAYER_THICKNESS = 200

ADDITIONAL_COLUMNS = ["corrected_depth", "fs", "u2", "inclination", "inclination_n_s", "inclination_e_w"]

GEF_FILE_ENCODING = "ISO-8859-1"

DEFAULT_SOIL_NAMES = [
    OptionListElement("Grind, zwak siltig, los"),
    OptionListElement("Grind, zwak siltig, matig"),
    OptionListElement("Grind, zwak siltig, vast"),
    OptionListElement("Grind, sterk siltig, los"),
    OptionListElement("Grind, sterk siltig, matig"),
    OptionListElement("Grind, sterk siltig, vast"),
    OptionListElement("Zand, schoon, los"),
    OptionListElement("Zand, schoon, matig"),
    OptionListElement("Zand, schoon, vast"),
    OptionListElement("Zand, zwak siltig, kleiïg"),
    OptionListElement("Zand, sterk siltig, kleiïg"),
    OptionListElement("Leem, zwak zandig, slap"),
    OptionListElement("Leem, zwak zandig, matig"),
    OptionListElement("Leem, zwak zandig, vast"),
    OptionListElement("Leem, sterk zandig"),
    OptionListElement("Klei, schoon, slap"),
    OptionListElement("Klei, schoon, matig"),
    OptionListElement("Klei, schoon, vast"),
    OptionListElement("Klei, zwak zandig, slap"),
    OptionListElement("Klei, zwak zandig, matig"),
    OptionListElement("Klei, zwak zandig, vast"),
    OptionListElement("Klei, sterk zandig"),
    OptionListElement("Klei, organisch, slap"),
    OptionListElement("Klei, organisch, matig"),
    OptionListElement("Veen, niet voorbelast, slap"),
    OptionListElement("Veen, matig voorbelast, matig"),
]

CPT_LEGEND = MapLegend(
    [
        (Color.green(), "CPT part of an already existing Section"),
        (Color.blue(), "CPT included and inside range of line"),
        (Color.viktor_yellow(), "CPT included but outside range of line"),
        (Color.red(), "CPT excluded"),
        (Color.lime(), "Borehole part of an already existing Section"),
        (Color.from_hex("00ffff"), "Borehole included and inside range of line"),
        (Color.from_hex("ffff00"), "Borehole included but outside range of line"),
        (Color.from_hex("ff007f"), "Borehole excluded"),
    ]
)

DEFAULT_ROBERTSON_TABLE = [
    {
        "name": "Robertson zone unknown",
        "ui_name": "Onbekend materiaal",
        "color": "255, 0, 0",
        "gamma_dry": 0,
        "gamma_wet": 0,
        "phi": 0,
    },
    {
        "name": "Robertson zone 1",
        "ui_name": "Grond, fijn korrelig",
        "color": "200, 25, 0",
        "gamma_dry": 10,
        "gamma_wet": 10,
        "phi": 15,
    },
    {
        "name": "Robertson zone 2",
        "ui_name": "Veen, organisch materiaal",
        "color": "188, 104, 67",
        "gamma_dry": 12,
        "gamma_wet": 12,
        "phi": 15,
    },
    {
        "name": "Robertson zone 3",
        "ui_name": "Klei, zwak siltig tot siltig",
        "color": "29, 118, 29",
        "gamma_dry": 15.5,
        "gamma_wet": 15.5,
        "phi": 17.5,
    },
    {
        "name": "Robertson zone 4",
        "ui_name": "Klei, siltig / leem",
        "color": "213, 252, 181",
        "gamma_dry": 18,
        "gamma_wet": 18,
        "phi": 22.5,
    },
    {
        "name": "Robertson zone 5",
        "ui_name": "Zand, siltig tot leem",
        "color": "213, 252, 155",
        "gamma_dry": 18,
        "gamma_wet": 20,
        "phi": 25,
    },
    {
        "name": "Robertson zone 6",
        "ui_name": "Zand, zwak siltig tot siltig",
        "color": "255, 225, 178",
        "gamma_dry": 18,
        "gamma_wet": 20,
        "phi": 27,
    },
    {
        "name": "Robertson zone 7",
        "ui_name": "Zand tot zand, grindig",
        "color": "255, 183, 42",
        "gamma_dry": 17,
        "gamma_wet": 19,
        "phi": 32.5,
    },
    {
        "name": "Robertson zone 8",
        "ui_name": "Zand, vast - zand, kleiig",
        "color": "200, 190, 200",
        "gamma_dry": 18,
        "gamma_wet": 20,
        "phi": 32.5,
    },
    {
        "name": "Robertson zone 9",
        "ui_name": "Grond, zeer stijf, fijnkorrelig",
        "color": "186, 205, 224",
        "gamma_dry": 20,
        "gamma_wet": 22,
        "phi": 40,
    },
]

DEFAULT_CLASSIFICATION_TABLE = [
    {
        "phi": 30,
        "name": "Zand, schoon, los",
        "color": "255,255,153",
        "qc_max": None,
        "qc_min": None,
        "rf_max": 0.8,
        "rf_min": None,
        "gamma_dry": 17,
        "gamma_wet": 19,
        "qc_norm_max": 5,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 32.5,
        "name": "Zand, schoon, matig",
        "color": "255,255,102",
        "qc_max": None,
        "qc_min": None,
        "rf_max": 0.8,
        "rf_min": None,
        "gamma_dry": 18,
        "gamma_wet": 20,
        "qc_norm_max": 15,
        "qc_norm_min": 5,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 35,
        "name": "Zand, schoon, vast",
        "color": "255,255,0",
        "qc_max": None,
        "qc_min": None,
        "rf_max": 0.8,
        "rf_min": None,
        "gamma_dry": 19,
        "gamma_wet": 21,
        "qc_norm_max": None,
        "qc_norm_min": 15,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 27,
        "name": "Zand, zwak siltig",
        "color": "255,204,102",
        "qc_max": None,
        "qc_min": None,
        "rf_max": 1.5,
        "rf_min": 0.8,
        "gamma_dry": 18,
        "gamma_wet": 20,
        "qc_norm_max": None,
        "qc_norm_min": 0,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 25,
        "name": "Zand, sterk siltig",
        "color": "255,204,0",
        "qc_max": None,
        "qc_min": None,
        "rf_max": 1.8,
        "rf_min": 1.5,
        "gamma_dry": 18,
        "gamma_wet": 20,
        "qc_norm_max": None,
        "qc_norm_min": 0,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 17.5,
        "name": "Klei, schoon, slap",
        "color": "0,255,0",
        "qc_max": 0.75,
        "qc_min": None,
        "rf_max": 5,
        "rf_min": 3,
        "gamma_dry": 14,
        "gamma_wet": 14,
        "qc_norm_max": None,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 17.5,
        "name": "Klei, schoon, matig",
        "color": "0,204,0",
        "qc_max": 1.5,
        "qc_min": 0.75,
        "rf_max": 5,
        "rf_min": 3,
        "gamma_dry": 17,
        "gamma_wet": 17,
        "qc_norm_max": None,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 17.5,
        "name": "Klei, schoon, vast",
        "color": "0,204,102",
        "qc_max": None,
        "qc_min": 1.5,
        "rf_max": 5,
        "rf_min": 3,
        "gamma_dry": 19,
        "gamma_wet": 19,
        "qc_norm_max": None,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 22.5,
        "name": "Klei, zwak zandig",
        "color": "102,255,102",
        "qc_max": None,
        "qc_min": 0,
        "rf_max": 3,
        "rf_min": 1.8,
        "gamma_dry": 18,
        "gamma_wet": 18,
        "qc_norm_max": None,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 27.5,
        "name": "Klei, sterk zandig",
        "color": "102,255,51",
        "qc_max": None,
        "qc_min": 0,
        "rf_max": 3,
        "rf_min": 1.8,
        "gamma_dry": 18,
        "gamma_wet": 18,
        "qc_norm_max": None,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 15,
        "name": "Klei, organisch, slap",
        "color": "102,153,0",
        "qc_max": 0.2,
        "qc_min": None,
        "rf_max": 7,
        "rf_min": 5,
        "gamma_dry": 13,
        "gamma_wet": 13,
        "qc_norm_max": None,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 15,
        "name": "Klei, organisch, matig",
        "color": "0,153,0",
        "qc_max": None,
        "qc_min": 0.2,
        "rf_max": 7,
        "rf_min": 5,
        "gamma_dry": 15,
        "gamma_wet": 15,
        "qc_norm_max": None,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 15,
        "name": "Veen niet voorbelast slap",
        "color": "204,153,0",
        "qc_max": 0.1,
        "qc_min": None,
        "rf_max": None,
        "rf_min": 7,
        "gamma_dry": 10,
        "gamma_wet": 10,
        "qc_norm_max": None,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
    {
        "phi": 15,
        "name": "Veen matig voorbelast matig",
        "color": "153,102,51",
        "qc_max": None,
        "qc_min": 0.1,
        "rf_max": None,
        "rf_min": 7,
        "gamma_dry": 12,
        "gamma_wet": 12,
        "qc_norm_max": None,
        "qc_norm_min": None,
        "max_cone_res_mpa": 0,
        "max_cone_res_type": "Standard",
    },
]
CLASSIFICATION_PARAMS = {
    "method": "robertson",
    "robertson": DEFAULT_ROBERTSON_TABLE,
    "table": DEFAULT_CLASSIFICATION_TABLE,
}
