REGIS_PRIMARY_FORMATION_NAME_CODE_MAPPING = {
    "HL": "Holocene afzettingen",
    "BX": "Fm. van Boxtel",
    "KR": "Fm. van Kreftenheye",
    "BE": "Fm. van Beegden",
    "KW": "Fm. van Koewacht",
    "WB": "Fm. van Woudenberg",
    "EE": "Een Fm.",
    "DR": "Fm. van Drente",
    "DT": "Gestuwde afzettingen",
    "DN": "Fm. van Drachten",
    "UR": "Fm. van Urk",
    "PE": "Fm. van Peele",
    "ST": "Fm. van Sterksel",
    "AP": "Fm. van Appelscha",
    "SY": "Fm. van Stramproy",
    "PZ": "Fm. van Peize",
    "WA": "Fm. van Waalre",
    "MS": "Fm. van Maassluis",
    "KI": "Kiezelooliet Fm.",
    "OO": "Fm. van OOsterhout",
    "IE": "Fm. van Inden",
    "BR": "Fm. van Breda",
    "VI": "Fm. van Ville",
    "VE": "Fm. van Veldhoven",
    "RU": "Rupel Fm.",
    "TO": "Fm. van Tongeren",
    "LA": "Fm. van Landen",
    "HT": "Fm. van Heijenrath",
    "HO": "Fm. van Houthem",
    "MT": "Fm. van Maastricht",
    "GU": "Fm. van Gulpen",
    "VA": "Fm. van Vaals",
    "DO": "Fm. van Dongen",
    "AK": "Fm. van Aken",
}

REGIS_SECONDARY_FORMATION_NAME_CODE_MAPPING = {
    "c": "complexe eenheid",
    "z": "zandige eenheid",
    "k": "kleiige eenheid",
    "v": "venige eenheid",
}

REGIS_MIDDLE_FORMATION_NAME_CODE_MAPPING = {
    "SC": "Lp. van Schimmert",
    "LM": "Lp. van Liempde",
    "WY": "Lp. van Wijchen",
    "RO": "Lp. van Rosmalen",
    "ZU": "Lp. van Zutphen",
    "TW": "Lp. van Twello",
    "UI": "Lp. van Uitdam",
    "GI": "Lp. van Gieten",
    "WA": "en Fm. van Waalre",
    "VO": "Lp. van Voort",
    "BO": "Lp. van Boom",
    "GO": "Lp. van Goudsberg",
    "AS": "Lp. van Asse",
}
